// ============================================================
// SMKN 2 YOGYAKARTA — Data Lengkap Hasil Riset Mendalam
// Sumber: https://www.smk2-yk.sch.id + Wikipedia + Kemdikbud
// ============================================================

export const sekolahInfo = {
  nama: "SMK Negeri 2 Yogyakarta",
  namaLama: "STM 1 Yogyakarta / Princess Juliana School (PJS)",
  motto: "Pelayanan Prima, Unggul dalam Mutu, Tinggi dalam Prestasi",
  tagline: "ISTIMEWA, PASTI, BISA",
  didirikan: 1919,
  alamat: "Jl. A.M. Sangaji No. 47, Cokrodiningratan, Jetis, Yogyakarta 55233",
  telepon: "(0274) 513490",
  fax: "(0274) 512639",
  email: "info@smk2-yk.sch.id",
  website: "https://www.smk2-yk.sch.id",
  luasTanah: "5,5 Hektar",
  luasBangunan: "16.000 m²",
  akreditasi: "A",
  sertifikasiISO: "ISO 9001:2008 (TÜV Rheinland)",
  statusSBI: "Sekolah Bertaraf Internasional (SBI INVEST 2009-2013)",
  statusCagarBudaya: true,
  sosialMedia: {
    instagram: "https://www.instagram.com/smkn2yogyakarta/",
    facebook: "https://www.facebook.com/SMK2YK/",
    youtube: "https://www.youtube.com/channel/UC-XjCCMZosDiXzBEKiS6FBA/videos",
    tiktok: "https://www.tiktok.com/@smk2yogyakarta",
    twitter: "https://twitter.com/smkn2yogyakarta",
  },
  visi: "Menghasilkan Tamatan Yang Berkarakter, Unggul, Berwawasan Lingkungan, dan Berdaya Saing Global",
  misi: [
    "Mengembangkan kurikulum pembelajaran berbasis Teaching Factory (TEFA)",
    "Mengembangkan budaya literasi numerik, digital, finansial, sains, dan bahasa",
    "Mengembangkan kompetensi peserta didik sesuai dengan bakat dan minat",
    "Menyelenggarakan pembelajaran dan manajemen sekolah berbasis TIK",
    "Meningkatkan fasilitas dan lingkungan belajar yang aman, nyaman, ramah lingkungan, ramah anak dan responsif gender",
    "Menerapkan Perilaku Ramah Lingkungan Hidup (PRLH) menuju sekolah adiwiyata nasional",
    "Mendampingi peserta didik dalam pembiasaan beribadah untuk meningkatkan ketaqwaan",
    "Menerapkan pendidikan berbasis Budaya Yogyakarta dan Profil Pelajar Pancasila",
    "Membangun kemitraan (Link and Match) dengan lembaga relevan dalam dan luar negeri",
    "Menyelenggarakan sertifikasi kompetensi dan bahasa asing bagi peserta didik",
  ],
};

export const jurusanData = [
  {
    id: 1,
    slug: "sija",
    title: "Sistem Informatika, Jaringan dan Aplikasi",
    shortName: "SIJA",
    icon: "Network",
    durasi: "4 Tahun",
    akreditasi: "A",
    description:
      "Program unggulan 4 tahun berstandar internasional. Menguasai cloud computing, keamanan siber, IoT, dan administrasi server. Lulusan langsung bersertifikasi Mikrotik Academy dan siap berkarir sebagai Network Engineer.",
    kompetensi: [
      "Merancang dan menginstalasi jaringan lokal (LAN) & luas (WAN)",
      "Mengadministrasi server berbasis Linux & Windows",
      "Membangun sistem keamanan jaringan (Network Security)",
      "Merancang dan mengoperasikan jaringan Wireless",
      "Instalasi dan konfigurasi VoIP",
      "Virtualisasi server dan cloud computing",
      "Merancang web database dan content management system",
    ],
    peluangKarir: [
      "Network Engineer / Administrator",
      "Cyber Security Analyst",
      "Cloud Infrastructure Engineer",
      "System Administrator",
      "Web Developer & Database Admin",
      "IT Consultant",
    ],
    mitraIndustri: [
      "PT. Telkom Akses",
      "PT. Wahana Lintas Nusa (WLAN)",
      "CV. Klop Solution",
      "UGM, UNY, UII, UIN Sunan Kalijaga",
    ],
    prestasi: [
      "Juara 1 Piala LIPI Kategori Desain Web — Akakom IT Fest 2016",
      "Juara 1 Kompetisi Web Sekolah Terbaik Nasional — AICTA 2012",
      "Penghargaan Khusus Kreatifitas Unggulan — FIKSI 2016",
      "Medali Emas Festival Inovasi dan Kewirausahaan Siswa Indonesia 2024",
    ],
  },
  {
    id: 2,
    slug: "tkro",
    title: "Teknik Kendaraan Ringan Otomotif",
    shortName: "TKRO",
    icon: "Car",
    durasi: "3 Tahun",
    akreditasi: "A",
    description:
      "Jurusan otomotif terlengkap dengan dukungan penuh dari Mitsubishi Motors. Belajar langsung dengan unit kendaraan asli (Outlander Sport) dari CSR KTB. Kurikulum CBT & PBE standar industri global.",
    kompetensi: [
      "Pemeliharaan mesin kendaraan ringan (OHV, OHC, EFI)",
      "Perbaikan sistem bahan bakar bensin (karburator & injeksi)",
      "Perawatan sistem kelistrikan dan penerangan kendaraan",
      "Perbaikan chasis, suspensi, rem, dan transmisi",
      "Engine Tune Up konvensional & EFI",
      "Perawatan sistem AC kendaraan",
      "Praktik Kerja Industri (Prakerin) selama 3 bulan",
    ],
    peluangKarir: [
      "Mekanik Bengkel Resmi (Toyota, Mitsubishi, Honda)",
      "Teknisi Otomotif Industri",
      "Quality Control Kendaraan",
      "Wirausaha Bengkel Mandiri",
      "Instruktur Pelatihan Otomotif",
    ],
    mitraIndustri: [
      "PT. Krama Yudha Tiga Berlian Motors (Mitsubishi)",
      "Toyota Indonesia",
      "Bengkel Resmi Wilayah DIY",
    ],
    prestasi: [
      "4 Medali Mitsubishi Technical Skill Contest 2025",
      "Juara LKS Otomotif Tingkat Provinsi DIY",
      "CSR Mitsubishi: Unit Outlander Sport GLS 2.0L untuk praktikum",
    ],
  },
  {
    id: 3,
    slug: "dkv",
    title: "Desain Komunikasi Visual / Multimedia",
    shortName: "DKV",
    icon: "Palette",
    durasi: "3 Tahun",
    akreditasi: "A",
    description:
      "Pusat kreativitas digital SMKN 2 Yogyakarta. Menguasai fotografi, videografi, animasi 2D/3D, desain grafis, dan UI/UX. Dilengkapi studio produksi profesional dan software industri terkini.",
    kompetensi: [
      "Desain grafis dan tipografi digital",
      "Fotografi dan videografi profesional",
      "Animasi 2D dan 3D",
      "Editing video dan post-production",
      "Desain UI/UX dan web design",
      "Produksi konten multimedia interaktif",
    ],
    peluangKarir: [
      "Graphic Designer",
      "Motion Graphics Artist",
      "UI/UX Designer",
      "Video Editor & Content Creator",
      "Fotografer Profesional",
      "Digital Marketing Specialist",
    ],
    mitraIndustri: ["Studio Kreatif Yogyakarta", "Agency Digital Nasional"],
    prestasi: [
      "Film Pendek FIKSI SMKN 2 YK masuk Festival Nasional",
      "Kontribusi aktif majalah sekolah Kuli Tinta",
    ],
  },
  {
    id: 4,
    slug: "titl",
    title: "Teknik Instalasi Tenaga Listrik",
    shortName: "TITL",
    icon: "Zap",
    durasi: "3 Tahun",
    akreditasi: "A",
    description:
      "Ahli kelistrikan industri dan rumah tangga. Menguasai instalasi panel listrik, sistem kendali PLC, dan otomasi industri. Peluang karir terbuka lebar di BUMN kelistrikan dan perusahaan manufaktur.",
    kompetensi: [
      "Instalasi penerangan dan tenaga listrik",
      "Pemasangan dan perawatan panel listrik",
      "Pengoperasian sistem kendali PLC (Programmable Logic Controller)",
      "Pemasangan instalasi motor listrik",
      "Pengukuran dan pengujian kelistrikan",
      "Sistem otomasi industri",
    ],
    peluangKarir: [
      "Teknisi Listrik PLN/BUMN",
      "Electrical Engineer Industri Manufaktur",
      "Teknisi Panel Listrik & Otomasi",
      "Kontraktor Instalasi Listrik",
      "Instruktur Kelistrikan",
    ],
    mitraIndustri: ["PLN Wilayah DIY", "Perusahaan Manufaktur Nasional"],
    prestasi: ["Kontestan LKS Electrical Installation Tingkat Nasional"],
  },
  {
    id: 5,
    slug: "tp",
    title: "Teknik Pemesinan",
    shortName: "TP",
    icon: "Cog",
    durasi: "3 Tahun",
    akreditasi: "A",
    description:
      "Jurusan legendaris sejak era STM 1. Menguasai mesin bubut, frais, gerinda, dan CNC (Computer Numerical Control). Lulusan menjadi teknisi presisi tinggi yang dibutuhkan industri manufaktur pesawat, otomotif, dan permesinan.",
    kompetensi: [
      "Pengoperasian mesin bubut konvensional",
      "Pengoperasian mesin frais konvensional",
      "Pemrograman dan pengoperasian mesin CNC (bubut & frais)",
      "Teknik pengelasan (SMAW, OAW, GMAW)",
      "Teknik pengecoran logam",
      "Gambar teknik mesin (manual & CAD)",
    ],
    peluangKarir: [
      "Operator & Programmer CNC",
      "Teknisi Manufaktur Otomotif & Dirgantara",
      "Welder / Juru Las Bersertifikat",
      "Quality Inspector Permesinan",
      "Wirausaha Bengkel Mesin",
    ],
    mitraIndustri: ["PT. Industri Manufaktur Nasional", "Bengkel Permesinan DIY"],
    prestasi: ["Juara LKS Turning/Milling Tingkat Provinsi DIY"],
  },
  {
    id: 6,
    slug: "dpib",
    title: "Desain Pemodelan dan Informasi Bangunan",
    shortName: "DPIB",
    icon: "Building2",
    durasi: "3 Tahun",
    akreditasi: "A",
    description:
      "Arsitektur dan teknik sipil era digital. Merancang gedung bertingkat menggunakan AutoCAD, SketchUp, dan BIM (Building Information Modeling). Menjadi drafter dan desainer bangunan profesional yang dibutuhkan kontraktor nasional.",
    kompetensi: [
      "Menggambar teknik bangunan manual & digital (AutoCAD)",
      "Pemodelan 3D dengan SketchUp dan BIM",
      "Merancang struktur beton bertulang",
      "Menghitung Rencana Anggaran Biaya (RAB)",
      "Membaca dan membuat denah, tampak, dan potongan bangunan",
      "Survey dan pengukuran tanah dasar",
    ],
    peluangKarir: [
      "Drafter / CAD Operator",
      "Desainer Interior & Arsitektur",
      "Estimator Konstruksi (RAB)",
      "Pengawas Proyek Bangunan",
      "Kontraktor Mandiri",
    ],
    mitraIndustri: ["Kontraktor Konstruksi DIY", "Konsultan Arsitektur"],
    prestasi: ["Juara LKS Bangunan Tingkat Provinsi DIY"],
  },
  {
    id: 7,
    slug: "kgsp",
    title: "Konstruksi Gedung, Sanitasi dan Perawatan",
    shortName: "KGSP",
    icon: "HardHat",
    durasi: "3 Tahun",
    akreditasi: "A",
    description:
      "Ahli konstruksi bangunan dan utilitas gedung. Menguasai teknik konstruksi batu beton, pemasangan sanitasi, dan perawatan gedung bertingkat. Lulusan siap bekerja di proyek-proyek infrastruktur besar.",
    kompetensi: [
      "Teknik konstruksi batu dan beton",
      "Pemasangan sistem sanitasi dan perpipaan",
      "Perawatan gedung dan bangunan",
      "Finishing dinding, lantai, dan plafon",
      "Pekerjaan perancah (scaffolding) sesuai K3",
      "Penerapan standar keamanan konstruksi",
    ],
    peluangKarir: [
      "Teknisi Konstruksi Bangunan",
      "Supervisor Proyek Infrastruktur",
      "Teknisi Perawatan Gedung (Building Maintenance)",
      "Instalator Sanitasi & Perpipaan",
      "Kontraktor Bangunan",
    ],
    mitraIndustri: ["BUMN Konstruksi", "Kontraktor Proyek DIY"],
    prestasi: ["Lulusan berkarir di proyek infrastruktur nasional"],
  },
  {
    id: 8,
    slug: "tav",
    title: "Teknik Audio Video",
    shortName: "TAV",
    icon: "Radio",
    durasi: "3 Tahun",
    akreditasi: "A",
    description:
      "Spesialis elektronika dan penyiaran. Menguasai sistem tata suara profesional, instalasi perangkat audio visual, perawatan peralatan broadcasting, dan teknologi elektronika terapan.",
    kompetensi: [
      "Instalasi sistem audio dan video profesional",
      "Teknik elektronika analog dan digital",
      "Perawatan dan perbaikan peralatan audio video",
      "Sistem tata suara (sound system) live event",
      "Teknik penyiaran dan broadcasting",
      "Instalasi CCTV dan sistem keamanan",
    ],
    peluangKarir: [
      "Sound Engineer / Teknisi Audio",
      "Broadcast Engineer Stasiun TV/Radio",
      "Teknisi Elektronika",
      "Instalator CCTV & Security System",
      "Teknisi Peralatan Studio",
    ],
    mitraIndustri: ["Stasiun TV & Radio Lokal", "Vendor Audio Visual"],
    prestasi: ["Bengkel TAV 3 lantai dari dana SBI Invest"],
  },
  {
    id: 9,
    slug: "geo",
    title: "Teknik Geomatika / Survey Pemetaan",
    shortName: "Geomatika",
    icon: "Map",
    durasi: "3 Tahun",
    akreditasi: "A",
    description:
      "Menjadi surveyor profesional dan ahli pemetaan modern. Menguasai teknologi GPS, pemetaan drone, pengolahan data spasial dengan GIS, dan levelling presisi untuk proyek infrastruktur berskala besar.",
    kompetensi: [
      "Pengukuran tanah (levelling, polygon, dan topografi)",
      "Pengoperasian Total Station dan GPS",
      "Pemetaan menggunakan drone (fotogrametri)",
      "Pengolahan data spasial dengan SIG (Sistem Informasi Geografis)",
      "Pembuatan peta tematik digital",
      "Cadastral survey (pemetaan lahan pertanahan)",
    ],
    peluangKarir: [
      "Surveyor & Geodesi Profesional",
      "Operator Drone Pemetaan",
      "GIS Analyst / Specialist",
      "Teknisi Pertanahan (BPN)",
      "Konsultan Survey Proyek Infrastruktur",
    ],
    mitraIndustri: ["BPN DIY", "Konsultan Survey Nasional"],
    prestasi: ["Program keahlian unik yang langka di SMK lain"],
  },
];

export const beritaData = [
  {
    id: 1,
    title: "Tim Adiwiyata SMKN 2 Yogya Gelar Aksi Bersih Sungai Peringati Hari Lingkungan Hidup",
    date: "10 Juni 2025",
    image: "/news-1.png",
    excerpt:
      "Sebagai sekolah berwawasan lingkungan, tim Adiwiyata SMKN 2 turun langsung membersihkan sungai dan lingkungan sekolah bersama ratusan siswa dan guru.",
  },
  {
    id: 2,
    title: "SMKN 2 Yogyakarta Raih 4 Medali di Mitsubishi Technical Skill Contest 2025",
    date: "12 Februari 2025",
    image: "/news-2.png",
    excerpt:
      "Membuktikan kualitas standar industri, siswa jurusan TKRO berhasil mendominasi kompetisi otomotif nasional yang diadakan langsung oleh Mitsubishi Motors Indonesia.",
  },
  {
    id: 3,
    title: "Siswa SMKN 2 Yogyakarta Raih Medali Emas FIKSI 2024 di Jakarta",
    date: "25 Oktober 2024",
    image: "/news-1.png",
    excerpt:
      "Karya inovasi teknologi dari tim SIJA sukses meraih medali emas di Festival Inovasi dan Kewirausahaan Siswa Indonesia tingkat nasional.",
  },
];

export const sejarahTimeline = [
  { tahun: "1919", event: "Didirikan sebagai Princess Juliana School (PJS) pada masa Hindia Belanda" },
  { tahun: "1951", event: "Ijazah pertama Sekolah Teknik Menengah Yogyakarta dikeluarkan" },
  { tahun: "1952", event: "Dipecah menjadi STM Negeri I (Bangunan & Kimia) dan STM Negeri II (Listrik & Mesin)" },
  { tahun: "1975", event: "Semua STM di kompleks Jetis digabung menjadi STM Yogyakarta I" },
  { tahun: "1997", event: "Resmi berubah nama menjadi SMK Negeri 2 Yogyakarta" },
  { tahun: "2007", event: "Gedung ditetapkan sebagai Cagar Budaya oleh Menteri Kebudayaan dan Pariwisata" },
  { tahun: "2008", event: "Meraih Sertifikat ISO 9001:2000 dari TÜV Rheinland, diserahkan oleh Mendikbud" },
  { tahun: "2009", event: "Ditetapkan sebagai Sekolah Bertaraf Internasional (SBI) melalui Proyek INVEST" },
  { tahun: "2015", event: "Menjadi Sekolah Rujukan Nasional & Sekolah Berintegritas (poin 99,6)" },
  { tahun: "Kini", event: "9 Program Keahlian, 100+ mitra industri, lulusan tersebar di seluruh Indonesia" },
];
