/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'on-tertiary': '#ffffff',
                'on-surface-variant': '#43474e',
                'on-error-container': '#93000a',
                'primary-fixed-dim': '#adc7f7',
                'on-surface': '#121c2c',
                'surface-tint': '#455f88',
                'on-error': '#ffffff',
                'outline': '#74777f',
                'inverse-on-surface': '#ebf1ff',
                'on-tertiary-fixed-variant': '#3c494e',
                'on-primary-container': '#86a0cd',
                'surface-container-highest': '#d9e3f9',
                'on-primary-fixed': '#001b3c',
                'on-primary': '#ffffff',
                'tertiary-fixed': '#d8e4eb',
                'secondary-container': '#66affe',
                'inverse-primary': '#adc7f7',
                'surface-container': '#e7eeff',
                'surface-container-high': '#dee8ff',
                'secondary-fixed-dim': '#9fcaff',
                'background': '#f9f9ff',
                'surface-container-lowest': '#ffffff',
                'on-tertiary-container': '#94a1a8',
                'inverse-surface': '#273141',
                'on-primary-fixed-variant': '#2d476f',
                'error': '#ba1a1a',
                'on-tertiary-fixed': '#111d22',
                'error-container': '#ffdad6',
                'on-background': '#121c2c',
                'tertiary-fixed-dim': '#bcc8cf',
                'primary-container': '#1a365d',
                'surface-bright': '#f9f9ff',
                'tertiary-container': '#2c383d',
                'outline-variant': '#c4c6cf',
                'secondary-fixed': '#d2e4ff',
                'primary-fixed': '#d6e3ff',
                'on-secondary-container': '#004172',
                'surface-variant': '#d9e3f9',
                'surface-container-low': '#f0f3ff',
                'on-secondary-fixed-variant': '#00497e',
                'tertiary': '#172328',
                'secondary': '#0061a5',
                'primary': '#002045',
                'on-secondary-fixed': '#001d37',
                'surface': '#f9f9ff',
                'surface-dim': '#d0daf0',
                'on-secondary': '#ffffff',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                gutter: '24px',
                xl: '64px',
                lg: '40px',
                sm: '16px',
                'container-max': '1280px',
                md: '24px',
                xs: '8px',
                base: '4px',
            },
            fontFamily: {
                'headline-lg-mobile': ['"Work Sans"', 'sans-serif'],
                'body-lg': ['"Public Sans"', 'sans-serif'],
                'body-md': ['"Public Sans"', 'sans-serif'],
                'headline-md': ['"Work Sans"', 'sans-serif'],
                'label-md': ['"Public Sans"', 'sans-serif'],
                'caption': ['"Public Sans"', 'sans-serif'],
                'headline-lg': ['"Work Sans"', 'sans-serif'],
                'display-lg': ['"Work Sans"', 'sans-serif'],
            },
            fontSize: {
                'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
            },
        },
    },
    plugins: [],
};
